Fix issue while loading image
While calling `set_source_surface`, Context argument was missing while
calling the respective C binding.

Error:

```
In lib/cairo/src/cairo/context.cr:282:16

 282 | LibCairo.set_source_surface(surface.to_unsafe, x, y)
                ^-----------------
Error: wrong number of arguments for 'Cairo::C::LibCairo#set_source_surface' (given 3, expected 4)
```

Signed-off-by: Aravinda Vishwanathapura <mail@aravindavk.in>