Indexable(T) now have unsafe_fetch instead of unsafe_at
https://crystal-lang.org/api/0.31.1/Indexable.html#unsafe_fetch(index:Int)-instance-method

    Error: abstract `def Indexable(T)#unsafe_fetch(index : Int)` must be implemented by Cairo::RectangleList